# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180712_1458'),
        ('blog', '0002_auto_20180712_1526'),
    ]

    operations = [
    ]
