# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180712_0957'),
        ('blog', '0003_merge_20180713_0720'),
    ]

    operations = [
    ]
