# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_merge_20180713_0749'),
        ('blog', '0004_merge_20180713_1214'),
    ]

    operations = [
    ]
