# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-30 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_member_assigned_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='assigned_jobs',
            new_name='assigned_job',
        ),
    ]
