# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-11 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180703_1248'),
        ('accounts', '0008_auto_20180704_0916'),
    ]

    operations = [
    ]
