# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-02 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160415_1824'),
        ('accounts', '0008_auto_20180630_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='assigned_job',
        ),
        migrations.AddField(
            model_name='member',
            name='assigned_job',
            field=models.ManyToManyField(null=True, to='api.Check'),
        ),
    ]
