# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180712_1458'),
        ('accounts', '0009_merge_20180713_0631'),
    ]

    operations = [
    ]
