# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-02 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160415_1824'),
        ('accounts', '0009_auto_20180702_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='assigned_job',
        ),
        migrations.AddField(
            model_name='member',
            name='assigned_jobs',
            field=models.ManyToManyField(to='api.Check'),
        ),
    ]
