# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20180713_0716'),
        ('accounts', '0009_auto_20180712_0957'),
    ]

    operations = [
    ]
