# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180711_0957'),
        ('accounts', '0010_merge_20180713_0716'),
    ]

    operations = [
    ]
