# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_merge_20180713_0748'),
        ('accounts', '0011_merge_20180713_0824'),
    ]

    operations = [
    ]
