# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_merge_20180716_1139'),
        ('accounts', '0016_merge_20180716_1532'),
    ]

    operations = [
    ]
