# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_merge_20180717_0752'),
        ('accounts', '0009_merge_20180711_1452'),
    ]

    operations = [
    ]
