# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_merge_20180713_0749'),
        ('accounts', '0020_auto_20180718_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[(b'high', b'High'), (b'low', b'Low'), (b'normal', b'Normal')], max_length=8)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Check')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Member')),
            ],
        ),
    ]
