# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-29 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160415_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='previous_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
