# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-04 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_check_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='Normal', max_length=6),
        ),
    ]
