# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_faq_tutorial'),
        ('api', '0028_auto_20180705_1045'),
    ]

    operations = [
    ]
