# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20180711_1606'),
        ('api', '0029_auto_20180712_1458'),
    ]

    operations = [
    ]
