# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-12 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_merge_20180712_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='nag_mode',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='off', max_length=4),
        ),
    ]
