# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-12 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180712_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='previous_ping',
            new_name='ping_before_last_ping',
        ),
    ]
