# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-11 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20180705_1045'),
        ('api', '0030_check_priority'),
    ]

    operations = [
    ]
