# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0031_merge_20180713_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackupTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=12)),
                ('file_name', models.CharField(max_length=100)),
                ('backups_period', models.CharField(default='Daily', max_length=10)),
                ('username', models.CharField(max_length=128)),
                ('password_hash', models.CharField(max_length=256)),
                ('error_message', models.CharField(max_length=100)),
                ('last_run_date', models.DateTimeField()),
                ('next_run_date', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
