# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-11 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20180710_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='previous_ping',
            new_name='ping_before_last_ping',
        ),
        migrations.AlterField(
            model_name='channel',
            name='kind',
            field=models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook'), ('hipchat', 'HipChat'), ('slack', 'Slack'), ('pd', 'PagerDuty'), ('po', 'Pushover'), ('victorops', 'VictorOps')], max_length=20),
        ),
    ]
