# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_merge_20180713_0823'),
        ('api', '0031_merge_20180713_0749'),
    ]

    operations = [
    ]
