# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_merge_20180716_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='video_link',
            field=models.URLField(help_text=b'https://www.youtube.com/embed/8m1uQa8u4QM'),
        ),
    ]
