# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_merge_20180713_0716'),
        ('api', '0033_merge_20180711_1422'),
    ]

    operations = [
    ]
