# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20180716_1309'),
        ('api', '0032_databasebackuptask'),
    ]

    operations = [
    ]
