# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_merge_20180717_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasebackuptask',
            name='database_kind',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgresSQL')], default='mysql', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='video_link',
            field=models.URLField(help_text='https://www.youtube.com/embed/8m1uQa8u4QM'),
        ),
    ]
