# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20180717_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasebackuptask',
            name='last_run_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
