# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20180717_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasebackuptask',
            name='database_name',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
    ]
