# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20180718_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediatask',
            name='post',
            field=models.TextField(),
        ),
    ]
