# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20180718_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtask',
            name='status',
            field=models.CharField(default='okay', max_length=10),
        ),
        migrations.AddField(
            model_name='socialmediatask',
            name='status',
            field=models.CharField(default='okay', max_length=10),
        ),
    ]
