# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_merge_20180719_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasebackuptask',
            name='database_kind',
            field=models.CharField(choices=[('postgresql', 'PostgresSQL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='databasebackuptask',
            name='ip_address',
            field=models.CharField(max_length=120),
        ),
    ]
